//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawingBoard {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceImp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceImp() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrawingBoard.ResourceImp", typeof(ResourceImp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BtmArrowDown {
            get {
                object obj = ResourceManager.GetObject("BtmArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmArrowLeft {
            get {
                object obj = ResourceManager.GetObject("BtmArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmArrowRight {
            get {
                object obj = ResourceManager.GetObject("BtmArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmArrowUp {
            get {
                object obj = ResourceManager.GetObject("BtmArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmBlack {
            get {
                object obj = ResourceManager.GetObject("BtmBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmBlue {
            get {
                object obj = ResourceManager.GetObject("BtmBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmBlueL {
            get {
                object obj = ResourceManager.GetObject("BtmBlueL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmBubbleEllipse {
            get {
                object obj = ResourceManager.GetObject("BtmBubbleEllipse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmBubbleRect {
            get {
                object obj = ResourceManager.GetObject("BtmBubbleRect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmCBrushThi {
            get {
                object obj = ResourceManager.GetObject("BtmCBrushThi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmChar {
            get {
                object obj = ResourceManager.GetObject("BtmChar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmChineseBrush {
            get {
                object obj = ResourceManager.GetObject("BtmChineseBrush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmColFill {
            get {
                object obj = ResourceManager.GetObject("BtmColFill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmColGet {
            get {
                object obj = ResourceManager.GetObject("BtmColGet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmCom {
            get {
                object obj = ResourceManager.GetObject("BtmCom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmCopy {
            get {
                object obj = ResourceManager.GetObject("BtmCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmCurve {
            get {
                object obj = ResourceManager.GetObject("BtmCurve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmCut {
            get {
                object obj = ResourceManager.GetObject("BtmCut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmCyan {
            get {
                object obj = ResourceManager.GetObject("BtmCyan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmDes {
            get {
                object obj = ResourceManager.GetObject("BtmDes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmDiamond {
            get {
                object obj = ResourceManager.GetObject("BtmDiamond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmDrag {
            get {
                object obj = ResourceManager.GetObject("BtmDrag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmEllipse {
            get {
                object obj = ResourceManager.GetObject("BtmEllipse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmEllipseR {
            get {
                object obj = ResourceManager.GetObject("BtmEllipseR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmGray {
            get {
                object obj = ResourceManager.GetObject("BtmGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmGrayL {
            get {
                object obj = ResourceManager.GetObject("BtmGrayL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmGreen {
            get {
                object obj = ResourceManager.GetObject("BtmGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmGreenL {
            get {
                object obj = ResourceManager.GetObject("BtmGreenL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmLine1 {
            get {
                object obj = ResourceManager.GetObject("BtmLine1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmLineStyle {
            get {
                object obj = ResourceManager.GetObject("BtmLineStyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmOriange {
            get {
                object obj = ResourceManager.GetObject("BtmOriange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmPaste {
            get {
                object obj = ResourceManager.GetObject("BtmPaste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmPaste1 {
            get {
                object obj = ResourceManager.GetObject("BtmPaste1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmPen {
            get {
                object obj = ResourceManager.GetObject("BtmPen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmPentagon {
            get {
                object obj = ResourceManager.GetObject("BtmPentagon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmPentagon1 {
            get {
                object obj = ResourceManager.GetObject("BtmPentagon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmPoint {
            get {
                object obj = ResourceManager.GetObject("BtmPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmPolygon {
            get {
                object obj = ResourceManager.GetObject("BtmPolygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmPurple {
            get {
                object obj = ResourceManager.GetObject("BtmPurple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmPurpleL {
            get {
                object obj = ResourceManager.GetObject("BtmPurpleL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmRed {
            get {
                object obj = ResourceManager.GetObject("BtmRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmRedL {
            get {
                object obj = ResourceManager.GetObject("BtmRedL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmRubber {
            get {
                object obj = ResourceManager.GetObject("BtmRubber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmSel {
            get {
                object obj = ResourceManager.GetObject("BtmSel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmSelMore {
            get {
                object obj = ResourceManager.GetObject("BtmSelMore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmSelRect {
            get {
                object obj = ResourceManager.GetObject("BtmSelRect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmSexangle {
            get {
                object obj = ResourceManager.GetObject("BtmSexangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmStar4 {
            get {
                object obj = ResourceManager.GetObject("BtmStar4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmStar5 {
            get {
                object obj = ResourceManager.GetObject("BtmStar5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmStar6 {
            get {
                object obj = ResourceManager.GetObject("BtmStar6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmStarLove {
            get {
                object obj = ResourceManager.GetObject("BtmStarLove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmThickness {
            get {
                object obj = ResourceManager.GetObject("BtmThickness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmTriangle {
            get {
                object obj = ResourceManager.GetObject("BtmTriangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmTriangle1 {
            get {
                object obj = ResourceManager.GetObject("BtmTriangle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtmYellow {
            get {
                object obj = ResourceManager.GetObject("BtmYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtpRect {
            get {
                object obj = ResourceManager.GetObject("BtpRect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
